AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ReceiptProcessor

Globals:
  Function:
    Timeout: 500 # This sets a global timeout of 10 seconds for all functions, which can be overridden

Resources:
  ProcessReceiptsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: receipts/
      Handler: process_receipts.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      Events:
        ProcessReceipts:
          Type: Api
          Properties:
            Path: /process_receipts
            Method: get
      Policies:
        - S3ReadPolicy:
            BucketName: my-receipts-bucket
        - S3WritePolicy:
            BucketName: result-receipts
        - Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action:
                - 'textract:AnalyzeDocument'
                - 'textract:DetectDocumentText'
                - 'bedrock:InvokeModel'
              Resource: '*'

Outputs:
#  ProcessReceiptsApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ProcessReceiptsFunction:
    Description: "ProcessReceipts Lambda Function ARN"
    Value: !GetAtt ProcessReceiptsFunction.Arn
  ProcessReceiptsFunctionIamRole:
    Description: "Implicit IAM Role created for ProcessReceipts function"
    Value: !GetAtt ProcessReceiptsFunctionRole.Arn

